# Generated by Django 5.1.7 on 2025-08-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
    ]
